language: 
  - php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: trusty
    - php: hhvm
      dist: trusty
    - php: 7.0
      dist: trusty
    - php: 7.1
      dist: trusty
    - php: 7.2
      dist: trusty
    - php: hhvm
      dist: trusty
    
before_install:
  - travis_retry composer self-update
install: 
  - travis_retry composer install --prefer-dist --no-interaction

before_script:

script: 
  - vendor/bin/phpunit
  