language: 
  - php

addons:
    apt:
        packages:
            - locales
            - language-pack-id
            - language-pack-fr

env:
    global:
        - LANG=id_ID.UTF-8
        - LC_ALL=id_ID.UTF-8

matrix:
  include:
    - php: 7.0
      env: LARAVEL_VERSION=5.5.*
    
    - php: 7.1
      env: LARAVEL_VERSION=5.5.*
    - php: 7.1
      env: LARAVEL_VERSION=5.6.*

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-interaction --no-update

install: 
  - travis_retry composer update --prefer-source --no-interaction

before_script:
  - export TZ=Asia/Jakarta

script: 
- vendor/bin/phpunit
